spring:
  application:
    name: estoque
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
management:
  endpoints:
    web:
      exposure:
        include: "*"
