spring:
  application:
    name: gateway
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: catalogo
          uri: lb://CATALOGO
          predicates:
            - Path=/catalogo/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG