spring:
  application:
    name: gateway
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
#        - name: CircuitBreaker
#          args:
#            name: requestcircuitbreaker
#            slidingWindowSize: 20
#            permittedNumberOfCallsInHalfOpenState: 5
#            waitDurationInOpenState: 10000
#            recordExceptions:
#              - feign.FeignException.ServiceUnavailable
#              - feign.FeignException.InternalServerError
#              - java.util.concurrent.TimeoutException
#              - java.io.IOException
#              - feign.FeignException.FeignServerException
#              - org.springframework.web.client.ResourceAccessException
        - name: Retry
          args:
            retries: 10
            statuses: BAD_GATEWAY
            methods: GET,POST
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValues: false
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 400
              burstCapacity: 450
              requestedTokens: 1
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s