spring:
  application:
    name: catalogo
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"