
spring:
  application:
    name: service-discover
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
